name: Setup Nix
description: "Install Nix with flakes enabled"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: "experimental-features = nix-command flakes"
